version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - echo Running tests...

  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - application.py
    - requirements.txt
    - Procfile
    - .ebextensions/**/*
    - temp.wav
  discard-paths: no
